version: '3.7'

services:
  springboot:
    image: springboot:0.0.1
    ports:
      - "9000:9000"
    networks:
      - app-net
    #secrets:
    #  - source : pogresql-connetion
    #    target : /app/fastapi/sql_info.json
    #healthcheck:
      #test: ["cmd", "curl","http://localhost:8000/api/check"]
      #interval: 1m
      #timeout: 10s
      #retries: 3
      #start_period: 30s
    deploy:
      replicas : 2
      update_config:
        parallelism: 1
        monitor: 60s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism : 1
        monitor : 0s
        failure_action : continue
        order : start-first
    #depends_on:
    #  - postgres
    #  - redis
      
  svelte:
      image: svelte:0.0.1
      ports:
        - "8080:80"
      networks:
        - app-net
      depends_on:
        - springboot
       # - fastapi-8001
      deploy:
        replicas : 2
  
  crawlling:
      image: crawlling:0.0.1

      
networks:
  app-net:
    #external:
      #name: nat
#volumes:
#  f945b2fb863622affc36f25e0d794d2029d13acda40fec3587ff4b810a540a63:
#    external : true
#  46ec0539ac913d3737fd9f9fa41e50147a001d57df40cf34b590587b2c2c4180:
#    external : true

#secrets:
#  pogresql-connetion:
#    file: ./sql_info.json
